env:
  global:
    - SECRET_KEY="baraka"
    - PORT=3000 
language: node_js
node_js:
  - 10.16.0
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
  - npm run coverage